pub mod catalog;
pub mod color;
pub mod cross_ref;
pub mod encoding;
pub mod error;
pub mod gradient;
pub mod graphics_state;
pub mod objects;
pub mod page;
pub mod pdf;
pub mod resources;
pub mod text;
pub mod util;
pub mod writer;

// Re-export main types for user API convenience
pub use error::{PdfError, PdfResult};
pub use gradient::ColorStop;
pub use graphics_state::GraphicsStateManager;
pub use objects::array::ArrayObject;
pub use objects::boolean::BooleanObject;
pub use objects::dictionary::DictionaryObject;
pub use objects::indirect::IndirectObject;
pub use objects::metadata::PdfMetadata;
pub use objects::name::NameObject;
pub use objects::number::{NumberObject, NumberType};
pub use objects::pdf_object::PdfObject;
pub use objects::stream::StreamObject as Stream;
pub use objects::stream::{CompressionMethod, StreamObject};
pub use objects::string::StringObject;
pub use page::{PageObject, PageSize};
pub use pdf::{FileIdentifierMode, PDF};
pub use resources::ResourceDictionary;
pub use text::{StandardFont, WrapMode, wrap_text};
